default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "bundleRelease")
    
    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['SERVICE_ACCOUNT_JSON'],
      package_name: 'ch.heuscher.airescuering'
    )
  end
end
